"""Probe alternative Open-Meteo archive models for the ERA5 boundary_layer_height gap (ADR-005).

Our ERA5 downloads have `boundary_layer_height` null for 2024-01-01 → 2024-06-30. This probe stays
within ~60 call units: (1) a 1-day screen per candidate model at one location, on a day inside and
a day outside the gap; (2) for models that return BLH inside the gap, a 2024-05-01 → 2024-08-31 request at two locations (May–Jun = inside the gap,
Jul–Aug = overlap with our ERA5 values for agreement statistics). Every request is appended to the
weather ledger so the downloader's rolling limits account for it.

Writes docs/blh_gap.md (facts; the recommendation paragraph is CONCLUSION below).

Run: uv run python -m pipeline.blh_probe
"""

import json
import time
from datetime import UTC, date, datetime

import numpy as np
import pandas as pd

from pipeline.config import DOCS, OPEN_METEO_ARCHIVE_URL, WEATHER_RAW
from pipeline.http import make_session
from pipeline.md import md_table
from pipeline.weather_download import LEDGER, LOCATIONS, append_ledger

CANDIDATES = ["era5", "era5_seamless", "era5_ensemble", "era5_land", "ecmwf_ifs",
              "ecmwf_ifs_analysis_long_window"]
SCREEN_DAYS = [date(2024, 3, 15), date(2024, 8, 15)]  # inside / outside the ERA5 gap
WINDOW = (date(2024, 5, 1), date(2024, 8, 31))
GAP_END = pd.Timestamp("2024-07-01", tz="UTC")
OUT_MD = DOCS / "blh_gap.md"
CACHE = WEATHER_RAW / "_blh_probe"
CONCLUSION = """
No Open-Meteo archive model can fill the gap. Only `era5` and `era5_seamless` return
`boundary_layer_height` at all, and both are null on 2024-03-15. ERA5-Ensemble, ERA5-Land and the
two IFS models return no BLH even on 2024-08-15. **Recommended option: a companion deweathering
model without BLH.** Train it on the same pre-treatment data and features minus BLH, and use it
only for the hours where BLH is missing (2024-01-01 → 2024-06-30). Report its out-of-sample metrics
next to the main model's, and run the analysis once with the no-BLH model everywhere as a
robustness check. Do not let LightGBM route the NaNs on its own: the training data has no missing
BLH, so that branch would be learned from nothing. A later upgrade, if time allows, is to fetch
BLH for H1 2024 directly from the Copernicus CDS (free account), which is outside this session's
tools.
"""


def request(session, loc, start: date, end: date, model: str) -> tuple[int, dict | str]:
    """Fetch BLH; successful responses are cached on disk so reruns spend no call units."""
    cache = CACHE / f"{loc['location_id']}_{model}_{start}_{end}.json"
    if cache.exists():
        return 200, json.loads(cache.read_text())
    days = (end - start).days + 1
    params = {"latitude": loc["lat"], "longitude": loc["lon"], "start_date": str(start),
              "end_date": str(end), "hourly": "boundary_layer_height", "models": model,
              "timezone": "UTC"}
    ts = time.time()
    r = session.get(OPEN_METEO_ARCHIVE_URL, params=params, timeout=120)
    append_ledger(ts, max(days / 14, 1.0), loc["location_id"], start.year,
                  f"blh_probe:{r.status_code}")
    if not r.ok:
        return r.status_code, r.text[:300]
    CACHE.mkdir(parents=True, exist_ok=True)
    cache.write_text(r.text)
    return r.status_code, r.json()


def series(payload: dict) -> pd.Series:
    h = payload["hourly"]
    return pd.Series(h["boundary_layer_height"],
                     index=pd.to_datetime(h["time"]).tz_localize("UTC"), dtype="float64")


def main() -> None:
    session = make_session(retry_on_429=False)
    locs = pd.read_parquet(LOCATIONS).sort_values("priority")
    # One DE location and the highest-priority location without a DE station.
    picks = [locs.iloc[0], locs[~locs["countries"].str.contains("DE")].iloc[0]]
    out = ["# Boundary-layer-height gap — alternative models", ""]
    out.append(f"Generated by `pipeline/blh_probe.py` on {datetime.now(UTC):%Y-%m-%d %H:%M} UTC. "
               "Facts first; recommendation at the end.")
    out.append("")
    out.append("Gap: in our ERA5 files (`models=era5`) `boundary_layer_height` is null for "
               "2024-01-01 00:00 → 2024-06-30 23:00 UTC; Jul–Dec 2024 and all other years are "
               "complete. Budget for this probe: ≤ 60 call units, so the comparison window is "
               f"{WINDOW[0]} → {WINDOW[1]} instead of the full year.")
    out.append("")

    # 1) Screen
    screen = []
    for day in SCREEN_DAYS:
        for m in CANDIDATES:
            code, data = request(session, picks[0], day, day, m)
            row = {"day": str(day), "model": m, "http": code}
            if isinstance(data, dict):
                s = series(data)
                row |= {"non_null_hours": int(s.notna().sum()), "hours": len(s),
                        "grid": f"{data['latitude']}, {data['longitude']}"}
            else:
                row |= {"error": data}
            screen.append(row)
    screen = pd.DataFrame(screen)
    out += [(f"## 1) Screen: BLH on {', '.join(map(str, SCREEN_DAYS))} at "
             f"`{picks[0]['location_id']}` ({picks[0]['lat']}, {picks[0]['lon']})"), "",
            "Hours with a non-null `boundary_layer_height` out of 24.", "", md_table(screen), ""]
    in_gap_day = screen[screen["day"] == str(SCREEN_DAYS[0])]
    usable = in_gap_day.loc[in_gap_day["non_null_hours"].fillna(0) > 0, "model"].tolist()
    usable = [m for m in usable if m != "era5"]

    # 2) Window comparison, only for models that have BLH inside the gap
    rows = []
    for loc in picks:
        ours = pd.read_parquet(WEATHER_RAW / loc["location_id"] / "2024.parquet")
        ours = ours.set_index("time_utc")["boundary_layer_height"]
        for m in usable:
            code, data = request(session, loc, *WINDOW, m)
            if not isinstance(data, dict):
                rows.append({"location_id": loc["location_id"], "model": m, "http": code,
                             "error": data})
                continue
            alt = series(data)
            in_gap = alt[alt.index < GAP_END]
            overlap = pd.concat([alt[alt.index >= GAP_END], ours], axis=1, join="inner").dropna()
            overlap.columns = ["alt", "era5"]
            diff = overlap["alt"] - overlap["era5"]
            rows.append({
                "location_id": loc["location_id"], "model": m, "http": code,
                "grid": f"{data['latitude']}, {data['longitude']}",
                "gap_hours_non_null": f"{int(in_gap.notna().sum())}/{len(in_gap)}",
                "overlap_hours": len(overlap),
                "bias_m": diff.mean(), "rmse_m": float(np.sqrt((diff ** 2).mean())),
                "corr": overlap["alt"].corr(overlap["era5"]),
                "era5_mean_m": overlap["era5"].mean(),
            })
    out += [(f"## 2) {WINDOW[0]} → {WINDOW[1]}: coverage in the gap (May–Jun) and agreement "
             "with our ERA5 BLH in Jul–Aug 2024"), ""]
    if rows:
        out += ["Bias = alternative − ERA5 (m). Correlation and RMSE over hourly values.", "",
                md_table(pd.DataFrame(rows)), ""]
    else:
        out += [("Not run: no candidate model returned BLH on the in-gap screen day, so there is "
                "nothing to compare."), ""]
    ledger = pd.read_csv(LEDGER)
    probe = ledger[ledger["status"].astype(str).str.startswith("blh_probe")]
    out += [(f"Call units used by all `blh_probe` runs (weather ledger, days/14 with a minimum of 1 "
            f"per request): {probe['units'].sum():.1f} in {len(probe)} requests."), ""]
    out += ["## Recommendation", "", CONCLUSION.strip(), ""]
    OUT_MD.write_text("\n".join(out))
    print("\n".join(out))


if __name__ == "__main__":
    main()
