"""Empirical check of the clock behind the tz-naive EEA `Start` timestamps.

1. Weekday diurnal NO2 profile (Jan–Feb 2019, urban traffic points) by country × metadata
   `Timezone` label × first-hour group, against raw `Start` hour. In Jan–Feb all study countries
   are on UTC+1 local time, so a clock shift shows up as a shifted rush-hour peak.
2. DST-switch-day test for one BE `UTC`, one FR `UTC` and one FR `UTC+01` file.
3. Files whose first `Start` is 01:00 on 1 January: profile lag against DE.

Writes docs/timezone_check.md. Needs data/processed/station_candidates.parquet
(run pipeline.station_funnel first).

Run: uv run python -m pipeline.timezone_check
"""

from datetime import UTC, date, datetime, timedelta

import duckdb
import numpy as np
import pandas as pd

from pipeline.config import DATA_PROCESSED, DOCS, EEA_E1A_DIR, VALID_CODES
from pipeline.md import md_table

CANDIDATES = DATA_PROCESSED / "station_candidates.parquet"
OUT_MD = DOCS / "timezone_check.md"
REFERENCE = ("DE", "UTC+01", "jan1_00")
MAX_LAG = 3

# Written after reviewing the facts this script produces; keep in sync with the numbers.
CONCLUSION = """{{CONCLUSION}}"""


def last_sunday(year: int, month: int) -> date:
    d = date(year, month + 1, 1) - timedelta(days=1)
    return d - timedelta(days=(d.weekday() + 1) % 7)


def first_hour_group(row) -> str:
    start = row["start_min"]
    if start.month == 1 and start.day == 1:
        return f"jan1_{start.hour:02d}"
    return "other"


def best_lag(profile: np.ndarray, reference: np.ndarray) -> tuple[int, float]:
    """Lag k (hours) maximising corr(profile[h], reference[h - k]); k > 0 = profile is later."""
    scores = {k: np.corrcoef(profile, np.roll(reference, k))[0, 1]
              for k in range(-MAX_LAG, MAX_LAG + 1)}
    k = max(scores, key=scores.get)
    return k, scores[k]


def main() -> None:
    cand = pd.read_parquet(CANDIDATES)
    cand = cand[cand["in_metadata"]].copy()
    cand["first_hour_group"] = cand.apply(first_hour_group, axis=1)
    cand["path"] = [str(EEA_E1A_DIR / c / f"{f}.parquet")
                    for c, f in zip(cand["country"], cand["file_point_id"], strict=True)]
    valid = ", ".join(str(c) for c in VALID_CODES)
    con = duckdb.connect()
    out = ["# Time-zone check — EEA E1a `Start` timestamps", ""]
    out.append(f"Generated by `pipeline/timezone_check.py` on "
               f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}. Hours are raw `Start` hours "
               f"(no conversion). Valid = `Validity` in {VALID_CODES}.")
    out.append("")

    # --- 1) Diurnal profiles -------------------------------------------------------
    sel = cand[(cand["station_area"] == "urban") & (cand["station_type"] == "traffic")]
    con.register("sel", sel[["sampling_point_id", "country", "timezone", "first_hour_group",
                             "path"]])
    prof = con.execute(f"""
        select s.country, s.timezone, s.first_hour_group,
               hour(r."Start") as hour, avg(r."Value"::double) as no2,
               count(distinct s.sampling_point_id) as points
        from read_parquet({sel["path"].tolist()}) r
        join sel s on s.sampling_point_id = regexp_replace(r."Samplingpoint", '^[A-Z]{{2}}/', '')
        where r."Start" >= '2019-01-01' and r."Start" < '2019-03-01'
          and isodow(r."Start") <= 5 and r."Validity" in ({valid})
        group by all
    """).df()
    groups = prof.groupby(["country", "timezone", "first_hour_group"])
    wide = prof.pivot_table(index="hour", columns=["country", "timezone", "first_hour_group"],
                            values="no2")
    ref = wide[REFERENCE].to_numpy()
    summary = []
    for key, g in groups:
        g = g.set_index("hour").reindex(range(24))
        morning = g.loc[3:12, "no2"]
        evening = g.loc[14:23, "no2"]
        lag, r = best_lag(wide[key].to_numpy(), ref) if g["no2"].notna().all() else (None, None)
        summary.append({
            "country": key[0], "timezone_label": key[1], "first_hour_group": key[2],
            "points": int(g["points"].max()),
            "morning_peak_hour": int(morning.idxmax()) if morning.notna().any() else None,
            "evening_peak_hour": int(evening.idxmax()) if evening.notna().any() else None,
            "min_hour": int(g["no2"].idxmin()) if g["no2"].notna().any() else None,
            "lag_vs_DE_h": lag, "corr_at_lag": r,
        })
    summary = pd.DataFrame(summary)
    out += ["## 1) Weekday diurnal NO2, urban traffic, Jan–Feb 2019", ""]
    out.append("Groups: country × metadata `Timezone` (latest row) × first-hour group "
               "(`jan1_HH` = file's first `Start` is 1 Jan at HH:00; `other` = file starts on "
               "another date). Morning peak = argmax over raw hours 03–12; evening peak = argmax "
               f"over 14–23. `lag_vs_DE_h` = shift (−{MAX_LAG}…+{MAX_LAG} h) that maximises the "
               f"correlation with the reference profile {'/'.join(REFERENCE)}; positive = later "
               "than DE.")
    out += ["", md_table(summary), ""]
    profile_table = wide.map(lambda v: "" if pd.isna(v) else f"{v:.1f}")
    profile_table.columns = ["/".join(c) for c in profile_table.columns]
    out += ["<details><summary>Full 24-h profiles (mean µg/m³ by raw `Start` hour)</summary>", "",
            md_table(profile_table.reset_index()), "", "</details>", ""]

    # --- 2) DST switch days ------------------------------------------------------------
    out += ["## 2) DST-switch-day test", ""]
    out.append("Rows with `Start` at 02:00 on the last Sunday of March / October. A local clock "
               "with summer time has 0 in March and 2 in October; a fixed-offset clock has 1 and 1. "
               "Also: duplicated `Start` values and gaps ≠ 1 h. File = urban traffic point with "
               "the most rows for that country × label.")
    out.append("")
    picks = [("BE", "UTC"), ("FR", "UTC"), ("FR", "UTC+01")]
    for country, tz in picks:
        pool = cand[(cand["country"] == country) & (cand["timezone"] == tz)
                    & (cand["station_area"] == "urban") & (cand["station_type"] == "traffic")]
        if pool.empty:
            out += [f"- {country} `{tz}`: no urban traffic file found", ""]
            continue
        pick = pool.sort_values(["n_rows", "sampling_point_id"], ascending=[False, True]).iloc[0]
        starts = con.execute(f"""select "Start" from read_parquet('{pick["path"]}')""").df()["Start"]
        rows = []
        for y in range(2018, 2026):
            mar, octo = last_sunday(y, 3), last_sunday(y, 10)
            rows.append({
                "year": y,
                "march_day": str(mar),
                "rows_at_02_march": int(((starts.dt.date == mar) & (starts.dt.hour == 2)).sum()),
                "october_day": str(octo),
                "rows_at_02_october": int(((starts.dt.date == octo) & (starts.dt.hour == 2)).sum()),
            })
        gaps = starts.sort_values().diff().value_counts().head(3)
        out.append(f"### {country} `{tz}` — `{pick['sampling_point_id']}` ({pick['n_rows']:,} rows, "
                   f"first `Start` {pick['start_min']}, last `Start` {pick['start_max']})")
        out += ["", f"- duplicated `Start`: {int(starts.duplicated().sum())}",
                f"- most common gaps: { {str(k): int(v) for k, v in gaps.items()} }", "",
                md_table(pd.DataFrame(rows)), ""]

    # --- 3) First-hour groups --------------------------------------------------------------
    out += ["## 3) Files by first `Start` hour (all matched E1a files)", ""]
    cand["last_is_jan1_00"] = (cand["start_max"].dt.month.eq(1) & cand["start_max"].dt.day.eq(1)
                               & cand["start_max"].dt.hour.eq(0))
    fh = (cand.groupby(["country", "timezone", "first_hour_group"], dropna=False)
              .agg(files=("sampling_point_id", "size"),
                   files_last_start_jan1_00=("last_is_jan1_00", "sum"))
              .reset_index())
    out += [md_table(fh), ""]
    out.append("Profile lag of each first-hour group vs DE is in the `lag_vs_DE_h` column of "
               "section 1 (urban traffic only).")
    out += ["", "## Conclusion", "", CONCLUSION.strip(), ""]
    OUT_MD.write_text("\n".join(out))
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
