"""docs/provisional_vs_final.md: every headline estimate, provisional vs final. Facts only.

Provisional = dashboard/data/{headline,meta}.json as committed in PROVISIONAL_COMMIT (the last
provisional export, 191 of 587 control stations); final = the current dashboard/data files.

Run: uv run python -m analysis.provisional_vs_final
"""

import json
import subprocess

import pandas as pd

from pipeline.config import DOCS, REPO_ROOT
from pipeline.md import md_table

PROVISIONAL_COMMIT = "0f60f8e"
DATA = REPO_ROOT / "dashboard" / "data"


def from_git(path: str) -> dict:
    out = subprocess.run(["git", "show", f"{PROVISIONAL_COMMIT}:{path}"], cwd=REPO_ROOT,
                         capture_output=True, text=True, check=True).stdout
    return json.loads(out)


def num(v) -> str:
    return "–" if v is None else f"{v:+.2f}"


def ci(r) -> str:
    return f"[{num(r['ci_low'])}, {num(r['ci_high'])}]"


def pl(r) -> str:
    return "–" if r["placebo_min"] is None else f"[{num(r['placebo_min'])}, {num(r['placebo_max'])}]"


def main() -> None:
    prov, fin = from_git("dashboard/data/headline.json"), json.loads((DATA / "headline.json")
                                                                     .read_text())
    pmeta, fmeta = from_git("dashboard/data/meta.json"), json.loads((DATA / "meta.json")
                                                                    .read_text())
    if fin["status"] != "FINAL":
        raise SystemExit(f"dashboard/data/headline.json is {fin['status']}, not FINAL")
    p = {r["id"]: r for r in prov["rows"]}
    rows = []
    for r in fin["rows"]:
        q = p.get(r["id"])
        rows.append({
            "id": r["id"], "outcome": r["outcome"],
            "estimate prov → final": f"{num(q['estimate']) if q else '–'} → {num(r['estimate'])}",
            "95 % CI provisional": ci(q) if q else "–", "95 % CI final": ci(r),
            "placebo range provisional": pl(q) if q else "–", "placebo range final": pl(r),
            "verdict provisional": q["verdict"] if q else "–", "verdict final": r["verdict"],
            "verdict changed": "yes" if q and q["verdict"] != r["verdict"] else "no",
            "stations DE / ctrl prov → final":
                f"{q['n_de']} / {q['n_ctrl']} → {r['n_de']} / {r['n_ctrl']}" if q else "–"})
    counts = pd.DataFrame([
        {"count": "control stations with predictions (all types)",
         "provisional": pmeta["control_stations_with_predictions"],
         "final": fmeta["control_stations_with_predictions"]},
        {"count": "control stations in study (all types)",
         "provisional": pmeta["control_stations_in_study"],
         "final": fmeta["control_stations_in_study"]},
        {"count": "panel stations DE (traffic + background)", "provisional":
         pmeta["n_stations"]["DE"], "final": fmeta["n_stations"]["DE"]},
        {"count": "panel stations controls (traffic + background)", "provisional":
         pmeta["n_stations"]["controls"], "final": fmeta["n_stations"]["controls"]},
        *[{"count": f"panel stations {cc}", "provisional": pmeta["n_stations"]["by_country"]
           .get(cc, 0), "final": n} for cc, n in fmeta["n_stations"]["by_country"].items()],
        {"count": "panel station-days", "provisional": f"{pmeta['n_station_days']:,}",
         "final": f"{fmeta['n_station_days']:,}"},
    ])
    out = ["# Provisional vs final results", "",
           (f"Provisional: `dashboard/data/headline.json` at commit `{PROVISIONAL_COMMIT}` "
            f"({prov['generated_utc']}). Final: `dashboard/data/headline.json` "
            f"({fin['generated_utc']}). Generated by `analysis/provisional_vs_final.py`. Same "
            "specifications, thresholds and rules (ADR-008, ADR-010); only the control set grew. "
            "Units: ratio_pct and commute_excess in % points, resid_ugm3 in µg/m³."), "",
           "## Station counts", "", md_table(counts), "",
           "## Every headline estimate", "", md_table(pd.DataFrame(rows)), ""]
    (DOCS / "provisional_vs_final.md").write_text("\n".join(out))
    print(f"Wrote {DOCS / 'provisional_vs_final.md'}")


if __name__ == "__main__":
    main()
